# Generated by Django 5.1.5 on 2025-02-27 17:03

import booking.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='allUserBookings',
            fields=[
                ('id', models.CharField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('movie_title', models.CharField(max_length=100)),
                ('show_date', models.DateField()),
                ('seats', models.CharField(max_length=100)),
                ('total_amount', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.CharField(default=booking.models.generate_booking_id, editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('total_amount', models.FloatField()),
                ('seats', models.ManyToManyField(to='movie.seat')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='draftBooking',
            fields=[
                ('id', models.CharField(default=booking.models.generate_booking_id, editable=False, max_length=16, primary_key=True, serialize=False, unique=True)),
                ('seats', models.ManyToManyField(to='movie.seat')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
