# Generated by Django 5.1.6 on 2025-02-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_draftbooking_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alluserbookings',
            name='show_date',
            field=models.DateTimeField(),
        ),
    ]
